language: php

php:
  - 5.6
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then vendor/bin/phpunit; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.1' ]]; then phpunit; fi
